Contact Form Portfolio Mobile Using Template 5
JuanDBta/my-portfolio pull request #3
Opened 2023-03-28 20:59 UTC by JuanDBta

In this branch (contact-form-ui) we made the following changes:

Add Contact Form section
Add Style to the Contact Form
Add Footer

2023-03-28 22:02 UTC, adel-gu requested changes
# Status: Required Changes ♻️ 

Hi @team

Good job so far! 👏🏼 however, There are some issues that you still need to work on to go to the next project but you are almost there! 🥇 🚀 

![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzAyZTQ1NjJjY2Y4MzM3OTIzNjM3MDY2ZjU3NThhMjgzMDkyOTAzYyZjdD1n/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights
- All input fields have the `required` attribute ✔️ 
- All input fields are wrapped in a single `form` element. ✔️ 
- Flex property is used to layout the form content ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-28 22:02 UTC, adel-gu commented on mobile.html
> +        <form action="" method="post" class="contact-form">
- [ ] The form suppose to integrate with [form spree](https://formspree.io/html/) so the action attribute should have a value similar to `https://formspree.io/f/{form_id}` 👍🏼

**NOTE:❗** Currently the Form is not sending data.

2023-03-28 22:02 UTC, adel-gu commented on mobile.html
> +            <input type="text" id="name" name="name" maxlength="30" value="Anastasiia" required>
- [ ] Please consider adding a meaningful placeholder such as `Your Full Name` to the name input.
- [ ] The input is not supposed to have an attribute `value` since the user will insert his corresponding value ✅.

2023-03-28 22:02 UTC, adel-gu commented on mobile.html
> +            <input type="email" id="email" name="email" value="anastasiia@gm..." required>
- [ ] The email input is not supposed to have an attribute value since the user will insert his corresponding value white_check_mark.

2023-03-28 22:02 UTC, adel-gu commented on mobile.html
> +            <textarea name="contact-descrip" id="contact-descrip" cols="30" rows="10"
- [ ] Kindly consider that the `textarea `element should have the validation that checks for accepting up to 500 chars as mentioned in the project requirements 👌🏼

2023-03-28 22:02 UTC, adel-gu commented on styles.css
> +.contact {
Please be aware of mobile screen sizes varies between **min 375px** and  **max 786px** and the project styling should follow the Mobile First approach basically you look at whatever screen you have right now as a mobile screen 💻 = 📱.

- [ ] Sorry this was supposed to be mentioned in previous reviews, please ensure to avoid setting any fixed widths to the project sections and elements only if it is necessary 👌🏼 because your portfolio layout is fixed to the width `375px` and it's not responsive on the range **min 375px** and  **max 786px** **including the contact section layout**.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/228375349-85101387-6b25-4d01-afa7-2908b420c378.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/228375541-5d7407c1-1b2c-4f2c-b908-e7f8a1374a63.png)

2023-03-28 22:05 UTC, adel-gu commented on styles.css
> +
- [ ] Since this is a group project, please consider adding all the contributed social account links to the  **README** documentation 👍🏼

2023-03-30 20:28 UTC, Shisui6 approved these changes
Hi Team, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights
- HTML form validation done right ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 20:41 UTC, merged